### ISSUE TITLE
joblib.externals.loky.process_executor.BrokenProcessPool

### ISSUE THREAD

**Issue by namakshenas** [stellatogrp/mro_experiments#5]
I ran the followoing line:

`python facility/facility.py --foldername facility/
`

And getting the below error:

```

joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\externals\loky\process_executor.py", line 618, in wait_result_broken_or_wakeup
    result_item = result_reader.recv()
  File "C:\Users\Monash\AppData\Local\Programs\Python\Python38\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'msg'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "facility/facility.py", line 336, in <module>
    results = Parallel(n_jobs=njobs)(
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\parallel.py", line 1098, in __call__
    self.retrieve()
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "C:\Users\Monash\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Monash\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\externals\loky\_base.py", line 26, in _invoke_callbacks
    callback(self)
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\parallel.py", line 385, in __call__
    self.parallel.dispatch_next()
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\parallel.py", line 834, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\_parallel_backends.py", line 556, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\externals\loky\reusable_executor.py", line 176, in submit
    return super().submit(fn, *args, **kwargs)
  File "C:\Users\Monash\PycharmProjects\mro_experiments\env\lib\site-packages\joblib\externals\loky\process_executor.py", line 1129, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.BrokenProcessPool: A result has failed to un-serialize. Please ensure that the objects returned by the function are always picklable.  
```

**Comment by Irina526** [comment]
Hi, thank you for the notice! I edited the imports a little, do you still get the same error? @namakshenas

**Comment by namakshenas** [comment]
Yeah, getting the same error. 

It seemed pandas is making the trouble but upgrading to 1.2 didn't help.

btw, you didn't include pandas in the requirement.txt.

ps. testing on python 3.8

**Comment by namakshenas** [comment]
You can find a verbose error log in the link below:

[log_error_mro_experiments_2022_11_14_v_01](https://github.com/namakshenas/MeanRobustOptimization/blob/main/log_error_mro_experiments_2022_11_14_v_01.txt)

**Comment by Irina526** [comment]
> Yeah, getting the same error.
> 
> It seemed pandas is making the trouble but upgrading to 1.2 didn't help.
> 
> btw, you didn't include pandas in the requirement.txt.
> 
> ps. testing on python 3.8

Noted! I recompiled the requirements with pandas, and am using pandas 1.3.5, with python 3.8. I do not seem to get the error with joblib/pandas. Could you please try this set-up and see if anything changes?

**Comment by namakshenas** [comment]
getting another error:
[log](https://github.com/namakshenas/MeanRobustOptimization/blob/main/log_error_mro_experiments_2022_11_14_v_02.txt)

btw, you missed scikit-learn in the requirements (and I needed to idependently run `pip install -U scikit-learn`)

**Comment by Irina526** [comment]
Ok, thank you for the feedback! Since the error on your computer seems to be with parallelizing the code, maybe you can try setting `njobs = 1` on line 375 of facility.py. If this doesn't work, you can try removing the entire joblib segment by replacing lines 375 - 379 with 
`results = {}`
`for r in range(R):
    results[r] = facility_experiment(r, n, m, Data, Data_eval,
                                     prob_facility_separate, N_tot, K_tot, K_nums,
                                     eps_tot, eps_nums, foldername)
`
This might take a while to complete running because of the large number of experiments.

**Comment by namakshenas** [comment]
setting `njobs =1`
getting this error:
`mosek.Error: rescode.err_missing_license_file(1008): License cannot be located. The default search path is ';C:\Users\Monash\mosek\mosek.lic;'.`

So, now everything boils down to mosek license which I'm unable to acquire (I'm graduated and I cannot ask for an academic license)

**Comment by namakshenas** [comment]
setting `njobs =1`
It worked fine.

**Comment by namakshenas** [comment]
To practically run the project with joblib (njobs>1), it seems that I need a machine with significant RAM memory. I guess!

Have you implemented your approach on a simple linear programming problem? then, we can compare it with the classical RO approaches in terms of conservatism/overprotection/reliability.
